### ISSUE TITLE
Add fire weather functionality into rrfs-workflow

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#15]
The fire weather domain capability was developed using its own production-like workflow.  We need to fold this functionality into the authoritative workflow for RRFS.

**Comment by BenjaminBlake-NOAA** [comment]
I think the approach here would be to incorporate the RRFSFW into the workflow as a 4th cycle type.  It will need to run after the RRFS since it uses the RRFS for ICs/BCs.  The make_grid/orog/sfc_climo tasks have to be run for every cycle since the grid's location changes, but the other jobs (e.g. forecast, post) are similar and won't need to be modified much if at all.

**Comment by MatthewPyle-NOAA** [comment]
This item is waiting on the shift of the RRFS parallel to rrfs-workflow (#??)
