### ISSUE TITLE
bufrsnd jobs not running (both deterministic and ensemble) in v0.7.9

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#221]
Not sure what changed, but seems to not be finding the "itag" file 

forrtl: severe (29): file not found, unit 11, file /lfs/f2/t2o/ptmp/emc/stmp/emc.lam/rrfs/v0.7.9/2024020300/bufrsnd/bufrpost/fort.11
Image              PC                Routine            Line        Source
rrfs_bufr.exe      000000000044178B  Unknown               Unknown  Unknown
rrfs_bufr.exe      00000000004624C2  Unknown               Unknown  Unknown
rrfs_bufr.exe      000000000040B9F4  MAIN__                     78  WRFBUFR.f
rrfs_bufr.exe      000000000040B952  Unknown               Unknown  Unknown
libc-2.31.so       00001456AD19A24D  __libc_start_main     Unknown  Unknown
rrfs_bufr.exe      000000000040B86A  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 11, file /lfs/f2/t2o/ptmp/emc/stmp/emc.lam/rrfs/v0.7.9/2024020300/bufrsnd/bufrpost/fort.11

**Comment by MatthewPyle-NOAA** [comment]
Made a local change to look for ./itag rather than itag, but system mostly not running since due to unrelated issue.

**Comment by MatthewPyle-NOAA** [comment]
12Z cycle appears to be running with the "ln -sf" change...still a question of why.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  I know with the upgrade to v0.7.9 that the real-time parallel updated to the most recent version of rrfs-workflow.  I wonder if something about the environment changed since the export commands stopped working.  There are some other script differences between exrrfs_bufrsnd.sh in v0.7.7 and v0.7.9 related to variable names, but nothing is jumping out at me why this would be different.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @BenjaminBlake-NOAA.  Will go ahead and open a PR with my local change, but will leave the original material there commented out for now.
