### ISSUE TITLE
Eliminate the use of .txt files indicating that certain prep tasks are done with the engineering tests

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#244]
This process creates issues if rerunning the same engineering test without cleaning out those .txt files.  Don't believe this would cause trouble for RRFSFW (will run prep codes each cycle).  Can just comment out the offending lines in the J-jobs.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  When I commit my local changes for the RRFS firewx xml, I think I will combine that with removing the make_grid_task_complete.txt, make_orog_task_complete.txt, and make_sfc_climo_task_complete.txt files from the workflow.  Are there any other text files this issue is referring to or just those three?
