### ISSUE TITLE
Meet NCO Standard - Remove application logic that reference envir

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/rrfs-workflow#398]
NCO standard require to remove all reference to the use of envir. Please review and modify as needed.

**Comment by MatthewPyle-NOAA** [comment]
@lgannoaa $envir is a standard variable (Table 1 in the v11 implementation standards).  Examples are given in the implementation standard of it being used in compath.py path definitions, etc.  Is your objection to having what I call backup definitions of the variable at the J-job level (since it is supposed to be defined at the job card level)?

`export envir=${envir:-prod}
`

**Comment by lgannoaa** [comment]
Yes Matt. It makes debug easy if defined in job card level.
Thanks

**Comment by BenjaminBlake-NOAA** [comment]
Closing this issue because definitions of envir have been removed from the J-jobs with PR #449
