### ISSUE TITLE
extrn_ics/lbcs tasks need to be integrated into make_ics/lbcs

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#97]
- The two tasks `extrn_ics` and `extrn_lbcs` should be removed and their functions should be integrated into the `make_ics` and `make_lbcs` tasks, respectively.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA @ShunLiu-NOAA  I am currently working on this issue for the RRFS workflow.  For the GET_GEFS_LBCS_FILES task, which is used by the RRFS ensemble, I will try to incorporate it into the make_lbcs task with an if statement like this one:
if [ extrn_mdl_name != GEFS ]; then
  retrieve LBCs as normal
elif [ extrn_mdl_name = GEFS ]; then
  retrieve GEFS files and do time interpolation using wgrib2, which is currently done as part of GET_GEFS_LBCS_FILES
fi

I think this should work because most of the script logic in GET_EXTRN_LBCS and GET_GEFS_LBCS_FILES is the same except for the wgrib2 interpolation stuff.

**Comment by BenjaminBlake-NOAA** [comment]
This issue was completed with PRs #278 , #284 , and #285.
